version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
      - ls -R
      - sam package
        --template-file template.yaml
        --output-template-file packaged-template-$(date +%Y%m%d%H%M%S).yml
artifacts:
  files:
    - packaged-template-*.yml
