version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ls -R
      - mvn clean package
      - sam build
artifacts:
  files:
    - packaged-template.yml
