version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
      - ls -R
      - sam package --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
